Class {
	#name : #BrSearchDummyOneObject,
	#superclass : #Object,
	#category : #'Brick-Examples-Search'
}

{ #category : #accessing }
BrSearchDummyOneObject >> announcementClass [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlBackground [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlBorder [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlPaint [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlTask [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlocElementId [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlocFloatRectangle [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asBlocVector [
	^ self yourself
]

{ #category : #converting }
BrSearchDummyOneObject >> asCachedTransformation [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asDictionary [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asElement [
	^ self yourself
]

{ #category : #converting }
BrSearchDummyOneObject >> asElementTransformation [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asForm [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asScale3D [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asStencil [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> asTranslate3D [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> blocDefiningMethod [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> blocMethodDefinition [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> cornerRadius [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> create [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> dependsOnElementChildren [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> enlargement [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> entryIdentifier [
	^ self yourself
]

{ #category : #'api - accessing' }
BrSearchDummyOneObject >> eventsToHandle [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> firstOrNil [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> freezeOrWithoutContext [
	^ self yourself
]

{ #category : #geometry }
BrSearchDummyOneObject >> groupsFromIntersectingPairs [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> gtNextReadyProcess [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> hasPropertiesToPropagateToChildren [
	^ self yourself
]

{ #category : #comparing }
BrSearchDummyOneObject >> hash [
	^ self yourself
]

{ #category : #factory }
BrSearchDummyOneObject >> horizontal [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> image [
	^ self yourself
]

{ #category : #initialization }
BrSearchDummyOneObject >> initialize [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> initializeAnnouncer [
	^ self yourself
]

{ #category : #geometry }
BrSearchDummyOneObject >> intersectingPairs [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> is2D [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> is3D [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocFinite [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocFiniteFloat [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocFiniteFloatPoint [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocPositive [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocPositiveFloat [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocPositivePoint [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocPulseLoopProcess [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isBlocUIProcess [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isEmpty [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isIdentity [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isLineBreak [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isNotEmpty [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isPoint2D [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isPoint3D [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isPureSeparator [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isPureTranslation [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> isSystemCursor [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isTransparent [
	^ self yourself
]

{ #category : #testing }
BrSearchDummyOneObject >> isVisible [
	^ self yourself
]

{ #category : #factory }
BrSearchDummyOneObject >> leftToRight [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> modifiers [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> nsView [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> opacity [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> paint [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> primaryLeftKey [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> primaryModifier [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> primaryRightKey [
	^ self yourself
]

{ #category : #factory }
BrSearchDummyOneObject >> rightToLeft [
	^ self yourself
]

{ #category : #other }
BrSearchDummyOneObject >> secondaryModifier [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> style [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> subscriber [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> type [
	^ self yourself
]

{ #category : #finalization }
BrSearchDummyOneObject >> unregister [
	^ self yourself
]

{ #category : #factory }
BrSearchDummyOneObject >> vertical [
	^ self yourself
]

{ #category : #accessing }
BrSearchDummyOneObject >> width [
	^ self yourself
]
