Extension { #name : #BrAnchoredCompositeStrategyEvaluation }

{ #category : #'*Brick-DevTool' }
BrAnchoredCompositeStrategyEvaluation >> gtConfigureDropdownPreferredExtentPreviewElement: anElement [
	self strategy gtConfigureDropdownPreferredExtentPreviewElement: anElement
]

{ #category : #'*Brick-DevTool' }
BrAnchoredCompositeStrategyEvaluation >> gtConfigureTooltipPreferredExtentPreviewElement: anElement [
	self strategy gtConfigureTooltipPreferredExtentPreviewElement: anElement
]
