Extension { #name : #BrAnchoredSingleStrategy }

{ #category : #'*Brick-DevTool' }
BrAnchoredSingleStrategy >> gtConfigureDropdownPreferredExtentPreviewElement: anElement [
	^ referencePoint gtConfigureDropdownPreferredExtentPreviewElement: anElement
]

{ #category : #'*Brick-DevTool' }
BrAnchoredSingleStrategy >> gtConfigureTooltipPreferredExtentPreviewElement: anElement [
	^ referencePoint gtConfigureTooltipPreferredExtentPreviewElement: anElement
]
