Extension { #name : #BrAnchoredReferencePoint }

{ #category : #'*Brick-DevTool' }
BrAnchoredReferencePoint >> gtConfigureDropdownPreferredExtentPreviewElement: anElement [
	"Configure element constraints"

	self subclassResponsibility
]

{ #category : #'*Brick-DevTool' }
BrAnchoredReferencePoint >> gtConfigureTooltipPreferredExtentPreviewElement: anElement [
	"Configure element constraints"

	self subclassResponsibility
]
