Class {
	#name : #BrMenuConstants,
	#superclass : #Object,
	#category : #'Brick-Menu - Support'
}

{ #category : #constants }
BrMenuConstants class >> defaultMenuItemBottomPadding [
	^ 3
]

{ #category : #constants }
BrMenuConstants class >> defaultMenuItemLeftPadding [
	^ 6
]

{ #category : #constants }
BrMenuConstants class >> defaultMenuItemRightPadding [
	^ 6
]

{ #category : #constants }
BrMenuConstants class >> defaultMenuItemTopPadding [
	^ 2
]
