"
I am {{gtClass:BrPopoverContainerVisibilityUpdater}}.
I keep menu container visible.
"
Class {
	#name : #BrPopoverContainerPermanentVisibilityUpdater,
	#superclass : #BrPopoverContainerVisibilityUpdater,
	#category : #'Brick-Menu - Support'
}

{ #category : #'api - updating' }
BrPopoverContainerPermanentVisibilityUpdater >> updateGiven: anAnchorElement firstTime: isFirstTimeDisplay [
	"Do not change menu container visibility"

	
]
